<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3sIHiDG\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3sIHiDG/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/Container3sIHiDG.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\Container3sIHiDG\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \Container3sIHiDG\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => '3sIHiDG',
    'container.build_id' => '9fd55777',
    'container.build_time' => 1764284616,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container3sIHiDG');
