<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTIgqKwB\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTIgqKwB/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerTIgqKwB.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerTIgqKwB\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerTIgqKwB\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'TIgqKwB',
    'container.build_id' => '0ddf6938',
    'container.build_time' => 1764031810,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTIgqKwB');
